### PR TITLE
Bound NbE variant

### PR DESCRIPTION
**Pull request by phadej**
It's not considerably faster, but the fact it works is in itself incredible.
This turns out to be quite elegant as renaming in `bound` is just `fmap`ping.

```
benchmarking nf/Bound/
time                 19.21 ms   (18.16 ms .. 20.33 ms)
                     0.963 R²   (0.905 R² .. 0.995 R²)
mean                 21.19 ms   (20.11 ms .. 23.09 ms)
std dev              3.411 ms   (1.653 ms .. 5.397 ms)
variance introduced by outliers: 70% (severely inflated)

benchmarking nf/BoundNbE/
time                 14.76 ms   (14.32 ms .. 15.23 ms)
                     0.994 R²   (0.990 R² .. 0.998 R²)
mean                 15.92 ms   (15.03 ms .. 18.97 ms)
std dev              3.880 ms   (858.9 μs .. 7.740 ms)
variance introduced by outliers: 87% (severely inflated)
```

### CODE REVIEW

**Comment by phadej** [comment]
I played a little more, and now this is slightly faster than `bound`, and about as fast as `Scoped`.

```
benchmarking nf/Scoped/
time                 5.146 ms   (5.123 ms .. 5.176 ms)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 5.166 ms   (5.150 ms .. 5.210 ms)
std dev              76.67 μs   (40.00 μs .. 141.2 μs)

benchmarking nf/DB/
time                 2.461 s    (2.414 s .. 2.528 s)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 2.407 s    (2.373 s .. 2.433 s)
std dev              33.61 ms   (21.05 ms .. 40.81 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking nf/Bound/
time                 20.17 ms   (19.91 ms .. 20.46 ms)
                     0.999 R²   (0.998 R² .. 1.000 R²)
mean                 20.07 ms   (19.94 ms .. 20.32 ms)
std dev              385.1 μs   (239.7 μs .. 630.6 μs)

benchmarking nf/BoundNbE/
time                 5.168 ms   (5.059 ms .. 5.273 ms)
                     0.996 R²   (0.989 R² .. 0.999 R²)
mean                 5.253 ms   (5.199 ms .. 5.503 ms)
std dev              267.5 μs   (96.05 μs .. 548.0 μs)
variance introduced by outliers: 29% (moderately inflated)
```

which isn't a surprise, as one can see the similarities.

**Comment by phadej** [comment]
And to give proper credit, I more or less following tricks @AndrasKovacs does. Maybe he can spot what to do better here still.

**Comment by phadej** [comment]
I changed structure so all three `bound` variants are shown. I also changed the `abstract1` for another variant, which is a trade-off.

For a random lambda Scoped is faster,
but all bound variants benefit from abstract1 change.

```
benchmarking rand/Scoped/
time                 606.9 μs   (600.6 μs .. 613.8 μs)
                     0.999 R²   (0.999 R² .. 1.000 R²)
mean                 612.0 μs   (608.5 μs .. 617.3 μs)
std dev              14.61 μs   (11.12 μs .. 19.01 μs)
variance introduced by outliers: 14% (moderately inflated)

benchmarking rand/Bound.Def/
time                 2.098 ms   (2.079 ms .. 2.123 ms)
                     0.998 R²   (0.997 R² .. 0.999 R²)
mean                 2.214 ms   (2.191 ms .. 2.236 ms)
std dev              79.12 μs   (69.96 μs .. 89.12 μs)
variance introduced by outliers: 20% (moderately inflated)

benchmarking rand/Bound.NbE/
time                 941.8 μs   (938.9 μs .. 944.9 μs)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 945.9 μs   (944.0 μs .. 948.7 μs)
std dev              7.975 μs   (5.678 μs .. 12.86 μs)

benchmarking rand/Bound.NbEClos/
time                 908.8 μs   (906.8 μs .. 911.0 μs)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 910.8 μs   (909.3 μs .. 913.0 μs)
std dev              6.040 μs   (4.492 μs .. 8.949 μs)
```

Conversion for `bound` is slower (100 μs -> 120 μs), 
(worst case) two traversals per lambda is slower.

```
benchmarking conv/Scoped
time                 20.08 μs   (19.99 μs .. 20.21 μs)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 20.21 μs   (20.11 μs .. 20.57 μs)
std dev              535.3 ns   (177.3 ns .. 1.172 μs)
variance introduced by outliers: 28% (moderately inflated)

benchmarking conv/Bound.Def
time                 120.9 μs   (120.7 μs .. 121.1 μs)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 120.8 μs   (120.4 μs .. 122.0 μs)
std dev              1.936 μs   (515.3 ns .. 3.960 μs)
variance introduced by outliers: 10% (moderately inflated)

benchmarking conv/Bound.NbE
time                 120.8 μs   (120.7 μs .. 120.9 μs)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 120.8 μs   (120.6 μs .. 120.9 μs)
std dev              477.9 ns   (358.3 ns .. 773.7 ns)

benchmarking conv/Bound.NbEClos
time                 120.6 μs   (120.5 μs .. 120.8 μs)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 120.7 μs   (120.6 μs .. 120.9 μs)
std dev              520.4 ns   (402.9 ns .. 684.8 ns)
```

For lennart lambda `NbEClos` looks like to be a winner
for well-scoped representations.

```
benchmarking nf/Scoped/
time                 5.103 ms   (5.095 ms .. 5.113 ms)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 5.094 ms   (5.089 ms .. 5.099 ms)
std dev              16.41 μs   (13.69 μs .. 20.28 μs)

benchmarking nf/Bound.Def/
time                 18.91 ms   (18.81 ms .. 19.04 ms)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 18.96 ms   (18.90 ms .. 19.03 ms)
std dev              153.1 μs   (123.0 μs .. 198.0 μs)

benchmarking nf/Bound.NbE/
time                 11.94 ms   (11.74 ms .. 12.16 ms)
                     0.997 R²   (0.995 R² .. 0.999 R²)
mean                 11.55 ms   (11.41 ms .. 11.70 ms)
std dev              382.6 μs   (316.2 μs .. 471.7 μs)
variance introduced by outliers: 10% (moderately inflated)

benchmarking nf/Bound.NbEClos/
time                 4.641 ms   (4.617 ms .. 4.664 ms)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 4.613 ms   (4.597 ms .. 4.627 ms)
std dev              45.69 μs   (39.31 μs .. 54.47 μs)
```

**Comment by AndrasKovacs** [comment]
This seems to be a fun attempt at using Bound in tolerably efficient evaluation. Preliminary comments, but I'll probably try to address these myself as well:

- By having de Bruijn indices in `Sem`, we have the usual problem of O(N) weakening, which is commonly solved by using De Bruijn levels in semantics instead. I'm fairly sure that an intrinsically well-scoped implementation with levels needs `unsafeCoerce` for no-op weakening, but perhaps it would be possible to put `unsafeCoerce` behind a sensible API. See @ekmett's [gist](https://gist.github.com/ekmett/460ba28a3655c47e84c4135bc17b856f).
- The `toScope` in `lower (Clos c)` and `lower (Hoas f)` seems to be an extra operation compared to usual NbE with DB indices. I don't yet get why it's there, or if it can be skipped.

It would be nice to benchmark a standard NbE against the Bound one as well.

**Comment by phadej** [comment]
@AndrasKovacs thanks for your comments!

- I think `toScope` is unavoidable. Recall that in `bound` the [`Scope b f a`](https://hackage.haskell.org/package/bound-2.0.2/docs/Bound-Scope.html) is not `f (Var b a)` but a `f (Var b (f a))`. And extra level allows to represent lifted values explicitly, but then we have other costs.

**Comment by phadej** [comment]
Cleaning up old PRs.

**Pull request closed without merging**
